# docker build -t react-ionic -f Dockerfile.prod .
# docker run -p 8080:80 react-ionic

# 使用 Nginx 官方提供的基础镜像
FROM nginx:alpine

# 清空 Nginx 默认的静态文件目录
RUN rm -rf /usr/share/nginx/html/*

# 将打包好的 dist 文件夹复制到 Nginx 默认的静态文件目录下
COPY dist /usr/share/nginx/html

# 暴露 Nginx 默认的 HTTP 端口
EXPOSE 80

# 启动 Nginx 服务
CMD ["nginx", "-g", "daemon off;"]
